Use OnlineShopping;

Insert Into Province(ProvinceName) Values('Sindh');
Insert Into Province(ProvinceName) Values('Punjab');
Insert Into Province(ProvinceName) Values('Khyber-Pakhtunkhwa');
Insert Into Province(ProvinceName) Values('Islamabad Capital Territory');
Insert Into Province(ProvinceName) Values('Balochistan');


-- USE OnlineShopping;

INSERT INTO City (cityname) VALUES
('Karachi'),
('Lahore'),
('Faisalabad'),
('Rawalpindi'),
('Gujranwala'),
('Peshawar'),
('Multan'),
('Hyderabad'),
('Islamabad'),
('Quetta'),
('Bahawalpur'),
('Sargodha'),
('Sialkot'),
('Sukkur'),
('Jhang'),
('Larkana'),
('Dera Ghazi Khan'),
('Shekhupura'),
('Kasur'),
('Rahim Yar Khan'),
('Gujrat'),
('Mardan'),
('Sahiwal'),
('Okara'),
('Wah Cantonment'),
('Mingora'),
('Mirpur Khas'),
('Chiniot'),
('Nawabshah'),
('Kāmoke'),
('Burewala'),
('Jhelum'),
('Sadiqabad'),
('Khanewal'),
('Hafizabad'),
('Kohat'),
('Jacobabad'),
('Shikarpur'),
('Muzaffargarh'),
('Khanpur'),
('Gojra'),
('Bahawalnagar'),
('Abbottabad'),
('Muridke'),
('Pakpattan'),
('Khuzdar'),
('Jaranwala'),
('Chishtian'),
('Daska'),
('Bhalwal'),
('Mandi Bahauddin'),
('Ahmadpur East'),
('Kamalia'),
('Tando Adam'),
('Khairpur'),
('Dera Ismail Khan'),
('Vehari'),
('Nowshera'),
('Dadu'),
('Wazirabad'),
('Khushab'),
('Charsada'),
('Swabi'),
('Chakwal'),
('Mianwali'),
('Tando Allahyar'),
('Kot Adu'),
('Turbat');